name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"   # Har kuni yarim tunda avtomatik yangilanadi
  workflow_dispatch:        # Qo'lda (manual) ishga tushirish imkoniyati
  push:
    branches:
      - main              # Main branchga kod yuklanganda ishlaydi

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # GitHub contribution graph asosida ilon animatsiyasini yaratish
      - name: Generate Snake (dark)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: gayratbekxaydarov
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Yaratilgan SVG fayllarni "output" branchiga yuklash
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
